# Generated by Django 5.2.3 on 2025-07-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='article_content_multilang',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='destination',
            name='article_content',
            field=models.TextField(blank=True),
        ),
    ]
