# Generated by Django 5.2.3 on 2025-07-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_article_content_multilang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese')], help_text='Language code (ISO 639-1)', max_length=10)),
                ('title', models.CharField(blank=True, help_text='SEO-optimized title for this language version', max_length=300)),
                ('content', models.TextField(help_text='Full golf guide content in Markdown format')),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for search engines', max_length=160)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from destination and language', max_length=300)),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Approximate word count for content management')),
                ('character_count', models.PositiveIntegerField(default=0, help_text='Character count for content management')),
                ('generated_by', models.CharField(choices=[('manual', 'Manual Entry'), ('ollama', 'Ollama LLM'), ('openai', 'OpenAI API'), ('imported', 'Data Import')], default='ollama', max_length=50)),
                ('generation_model', models.CharField(blank=True, help_text="Specific model used for generation (e.g., 'llama3.1:70b')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_generated_at', models.DateTimeField(blank=True, help_text='When this content was last regenerated', null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='destinations.destination')),
            ],
            options={
                'ordering': ['destination__name', 'language_code'],
                'indexes': [models.Index(fields=['language_code', 'destination'], name='destination_languag_55615a_idx'), models.Index(fields=['destination', 'language_code'], name='destination_destina_5d4baf_idx'), models.Index(fields=['slug'], name='destination_slug_764ff7_idx')],
                'unique_together': {('destination', 'language_code')},
            },
        ),
    ]
