# Generated by Django 5.2.3 on 2025-07-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_modular_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='modular_reviews',
            new_name='modular_guides',
        ),
    ]
