# Generated by Django 5.2.3 on 2025-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_rename_modular_reviews_destination_modular_guides'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='destinationguide',
            index=models.Index(fields=['destination'], name='destination_destina_7d3987_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationguide',
            index=models.Index(fields=['language_code'], name='destination_languag_f9dd3d_idx'),
        ),
    ]
