# Generated by Django 5.2.3 on 2025-07-07 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_remove_destination_modular_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, default='en', max_length=10)),
                ('slug', models.SlugField(max_length=200)),
                ('overview', models.TextField(help_text='City overview and introduction')),
                ('neighborhoods', models.JSONField(default=dict, help_text='Neighborhoods: {name: {description, highlights, best_for}}')),
                ('attractions', models.JSONField(default=dict, help_text='Must-see attractions: {name: {description, category, tips}}')),
                ('dining', models.JSONField(default=dict, help_text='Restaurants & cuisine: {name: {description, cuisine_type, price_range}}')),
                ('nightlife', models.JSONField(default=dict, help_text='Bars, clubs, entertainment: {name: {description, type, atmosphere}}')),
                ('shopping', models.JSONField(default=dict, help_text='Shopping areas & markets: {name: {description, specialty, price_range}}')),
                ('transportation', models.JSONField(default=dict, help_text='Getting around: {type: {description, cost, tips}}')),
                ('accommodation', models.JSONField(default=dict, help_text='Where to stay: {name: {description, area, price_range}}')),
                ('seasonal_guide', models.JSONField(default=dict, help_text='Seasonal recommendations: {season: {weather, activities, events}}')),
                ('practical_info', models.JSONField(default=dict, help_text='Practical travel info: {category: {details, tips}}')),
                ('golf_summary', models.TextField(blank=True, help_text='Brief golf overview with link to full golf guide')),
                ('content_quality_score', models.FloatField(default=0.0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_guides', to='destinations.destination')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['destination', 'language_code'], name='destination_destina_81fbc5_idx'), models.Index(fields=['language_code'], name='destination_languag_83021f_idx'), models.Index(fields=['slug'], name='destination_slug_f98a81_idx'), models.Index(fields=['is_published', 'is_featured'], name='destination_is_publ_b08807_idx'), models.Index(fields=['updated_at'], name='destination_updated_85cb2f_idx')],
                'unique_together': {('destination', 'language_code')},
            },
        ),
    ]
