# Generated by Django 5.2.3 on 2025-07-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_cityguide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityguide',
            options={'ordering': ['destination__name', 'language_code']},
        ),
        migrations.AddField(
            model_name='cityguide',
            name='character_count',
            field=models.PositiveIntegerField(default=0, help_text='Character count for content management'),
        ),
        migrations.AddField(
            model_name='cityguide',
            name='generated_by',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('template', 'Template Generator'), ('ollama', 'Ollama LLM'), ('openai', 'OpenAI API'), ('imported', 'Data Import')], default='template', help_text='Method used to generate this content', max_length=50),
        ),
        migrations.AddField(
            model_name='cityguide',
            name='generation_model',
            field=models.CharField(blank=True, help_text="Specific model used for generation (e.g., 'llama3.1:70b')", max_length=100),
        ),
        migrations.AddField(
            model_name='cityguide',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, help_text='When this content was last regenerated', null=True),
        ),
        migrations.AddField(
            model_name='cityguide',
            name='title',
            field=models.CharField(blank=True, help_text='SEO-optimized title for this language version', max_length=300),
        ),
        migrations.AlterField(
            model_name='cityguide',
            name='content_quality_score',
            field=models.FloatField(default=0.0, help_text='Content quality score (0-100)'),
        ),
        migrations.AlterField(
            model_name='cityguide',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this guide is featured on the homepage'),
        ),
        migrations.AlterField(
            model_name='cityguide',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether this guide is published and visible'),
        ),
        migrations.AlterField(
            model_name='cityguide',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese')], help_text='Language code (ISO 639-1)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cityguide',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for search engines', max_length=160),
        ),
        migrations.AlterField(
            model_name='cityguide',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from destination and language', max_length=300),
        ),
        migrations.AlterField(
            model_name='cityguide',
            name='word_count',
            field=models.PositiveIntegerField(default=0, help_text='Approximate word count for content management'),
        ),
        migrations.AddIndex(
            model_name='cityguide',
            index=models.Index(fields=['language_code', 'destination'], name='destination_languag_eee6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='cityguide',
            index=models.Index(fields=['destination'], name='destination_destina_d68ebc_idx'),
        ),
    ]
